version: '3'

# 名前つきボリューム
volumes:
  mysql_data:
services:
  multi_factor_authentication:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/multi_factor_authentication/'
    ports:
      - '3005:3005'
    tty: true
    stdin_open: true
    depends_on:
      - db
    links:
      - db:database
    networks:
      - default

  db:
    image: mysql:8.0
    volumes:
      - 'mysql_data:/var/lib/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3310:3310'

